import json
import re
from typing import Any, Dict, Optional, Type, TypeVar
from pydantic import BaseModel
import httpx

from src.core.config import settings
from src.core.exceptions import LLMClientException
from src.core.logging import logger

T = TypeVar("T", bound=BaseModel)


class LLMResponse(BaseModel):
    text: str
    parsed_json: Optional[Dict[str, Any]] = None
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cost: float = 0.0
    model: str = "mock-model"


class MockLLMProvider:
    """High-fidelity simulated intelligence engine for reliable local tests and offline execution"""

    @staticmethod
    def generate_response(prompt: str, system_prompt: str, agent_type: str) -> LLMResponse:
        agent_type_upper = agent_type.upper()
        
        if "COO" in agent_type_upper or "AI_COO" in agent_type_upper:
            data = {
                "summary": "Deconstructed request into structured agile workflow with human gate and QA verification.",
                "request_type": "FEATURE",
                "priority_level": 4,
                "workflow_steps": [
                    {"name": "ANALYSIS", "agent": "BUSINESS_ANALYST", "type": "SPECIFICATION", "description": "Draft specifications and business rules"},
                    {"name": "REQUIREMENT_APPROVAL", "agent": "HUMAN", "type": "REQUIREMENT_APPROVAL", "description": "Review and approve specification"},
                    {"name": "DEVELOPMENT", "agent": "DEVELOPER", "type": "IMPLEMENTATION", "description": "Implement feature code and unit tests"},
                    {"name": "QA", "agent": "QA", "type": "VERIFICATION", "description": "Run automated test suite and check acceptance criteria"},
                    {"name": "FINAL_APPROVAL", "agent": "HUMAN", "type": "FINAL_APPROVAL", "description": "Final signoff and release"}
                ],
                "required_agents": ["BUSINESS_ANALYST", "DEVELOPER", "QA", "KNOWLEDGE"],
                "estimated_complexity": "MEDIUM",
                "reasoning": "Standard feature pipeline ensuring high code quality via specification gating and automated QA."
            }
        elif "ANALYST" in agent_type_upper or "BUSINESS_ANALYST" in agent_type_upper:
            data = {
                "title": "Feature Specification & Acceptance Criteria",
                "summary": "Detailed technical requirements breakdown based on user request and company architecture guidelines.",
                "requirements": [
                    {
                        "title": "Core Domain Model & Service Layer",
                        "description": "Implement business logic with full input validation and error handling.",
                        "priority": 4,
                        "business_rules": [
                            "Input validation must prevent malformed payloads",
                            "All database transactions must be atomic and idempotent",
                            "Sensitive fields must be sanitized in logs"
                        ],
                        "acceptance_criteria": [
                            "Given valid input parameters, when processed, then the system returns HTTP 200/201 with the created resource.",
                            "Given duplicate or invalid payloads, the system returns clear 400/409 validation error details.",
                            "Given an unexpected exception, the system logs the error securely and returns a structured 500 response."
                        ]
                    }
                ],
                "acceptance_criteria": [
                    "All endpoints pass schema validation",
                    "Database state is consistently persisted",
                    "Unit test suite achieves >= 90% code coverage"
                ],
                "business_rules": [
                    "Must comply with modular architecture standards",
                    "Async I/O for all external database and network calls"
                ],
                "open_questions": [],
                "tasks": [
                    "Create service and entity schemas",
                    "Implement logic and route handlers",
                    "Write automated pytest test suite"
                ]
            }
        elif "DEVELOPER" in agent_type_upper:
            # Code to be generated
            feature_code = '''"""
Feature Implementation - Generated by AI Developer
"""
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field

class FeaturePayload(BaseModel):
    name: str = Field(..., min_length=1)
    description: Optional[str] = None
    enabled: bool = True

class FeatureService:
    def __init__(self):
        self._store: Dict[str, Dict[str, Any]] = {}

    def create_item(self, item_id: str, payload: FeaturePayload) -> Dict[str, Any]:
        if not item_id:
            raise ValueError("Item ID cannot be empty")
        if item_id in self._store:
            raise ValueError(f"Item '{item_id}' already exists")
        data = payload.model_dump()
        data["id"] = item_id
        self._store[item_id] = data
        return data

    def get_item(self, item_id: str) -> Optional[Dict[str, Any]]:
        return self._store.get(item_id)
'''
            test_code = '''"""
Automated Pytest Suite - Generated by AI Developer
"""
import pytest
from src.features.service import FeatureService, FeaturePayload

def test_feature_service_creation():
    service = FeatureService()
    payload = FeaturePayload(name="Alpha Test", description="Automated QA run", enabled=True)
    res = service.create_item("item-101", payload)
    assert res["id"] == "item-101"
    assert res["name"] == "Alpha Test"
    assert service.get_item("item-101") == res

def test_duplicate_item_raises_error():
    service = FeatureService()
    payload = FeaturePayload(name="Beta", description="Duplicate check", enabled=True)
    service.create_item("item-202", payload)
    with pytest.raises(ValueError):
        service.create_item("item-202", payload)
'''
            data = {
                "technical_plan": [
                    "1. Define domain models with Pydantic validation",
                    "2. Implement core service logic and repository methods",
                    "3. Build comprehensive pytest test suite covering edge cases"
                ],
                "files_created": ["src/features/service.py", "tests/test_feature_service.py"],
                "files_modified": [],
                "tests_created": ["tests/test_feature_service.py"],
                "commit_hash": "a1b2c3d4e5f6",
                "commit_message": "feat: Implement requested feature service and test coverage",
                "summary": "Implemented feature service logic and wrote comprehensive automated tests.",
                "all_tests_passed": True,
                "file_contents": {
                    "src/features/service.py": feature_code,
                    "tests/test_feature_service.py": test_code,
                }
            }
        elif "QA" in agent_type_upper:
            data = {
                "status": "PASSED",
                "total_tests": 2,
                "passed_tests": 2,
                "failed_tests": 0,
                "coverage_percentage": 100.0,
                "bugs": [],
                "requirement_verification": {
                    "Given valid input parameters, returns resource": True,
                    "Given duplicate payload, returns error": True,
                    "Code follows modular standards": True
                },
                "summary": "All 2 automated tests passed with 100% coverage. Acceptance criteria fully satisfied."
            }
        elif "KNOWLEDGE" in agent_type_upper:
            data = {
                "extracted_insights": [
                    {
                        "category": "PATTERN",
                        "content": "Modular feature service architecture with pydantic validation and unit tests is established.",
                        "importance": 8
                    },
                    {
                        "category": "LESSON",
                        "content": "Automated pytest verification ensures zero regressions and smooth CI passes.",
                        "importance": 7
                    }
                ],
                "indexed_documents_count": 1,
                "summary": "Extracted architectural patterns and stored operational memories in Company Brain."
            }
        else:
            data = {"status": "SUCCESS", "message": "Executed successfully"}

        text_output = json.dumps(data, indent=2)
        prompt_tokens = len(prompt.split()) * 2 + 50
        completion_tokens = len(text_output.split()) * 2
        total_tokens = prompt_tokens + completion_tokens
        cost = (prompt_tokens * 0.000005) + (completion_tokens * 0.000015)

        return LLMResponse(
            text=text_output,
            parsed_json=data,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            cost=round(cost, 6),
            model="simulated-gpt4o",
        )


class LLMClient:
    """Unified LLM Client abstraction with fallback support"""

    def __init__(self, provider: Optional[str] = None):
        self.provider = provider or settings.LLM_PROVIDER

    async def chat(
        self,
        prompt: str,
        system_prompt: str = "",
        agent_type: str = "GENERAL",
        model: Optional[str] = None,
        temperature: float = 0.2,
        response_model: Optional[Type[T]] = None,
    ) -> LLMResponse:
        model_name = model or settings.DEFAULT_SMART_MODEL

        # Real OpenAI Provider
        if self.provider == "openai" and settings.OPENAI_API_KEY and settings.OPENAI_API_KEY != "mock-key":
            try:
                async with httpx.AsyncClient(timeout=60.0) as client:
                    messages = []
                    if system_prompt:
                        messages.append({"role": "system", "content": system_prompt})
                    messages.append({"role": "user", "content": prompt})

                    payload = {
                        "model": model_name,
                        "messages": messages,
                        "temperature": temperature,
                        "response_format": {"type": "json_object"},
                    }
                    headers = {
                        "Authorization": f"Bearer {settings.OPENAI_API_KEY}",
                        "Content-Type": "application/json",
                    }
                    res = await client.post("https://api.openai.com/v1/chat/completions", json=payload, headers=headers)
                    res.raise_for_status()
                    data = res.json()
                    choice = data["choices"][0]["message"]["content"]
                    usage = data.get("usage", {})
                    prompt_toks = usage.get("prompt_tokens", 0)
                    compl_toks = usage.get("completion_tokens", 0)
                    total_toks = usage.get("total_tokens", prompt_toks + compl_toks)
                    cost = (prompt_toks * 0.000005) + (compl_toks * 0.000015)

                    parsed = json.loads(choice)
                    return LLMResponse(
                        text=choice,
                        parsed_json=parsed,
                        prompt_tokens=prompt_toks,
                        completion_tokens=compl_toks,
                        total_tokens=total_toks,
                        cost=round(cost, 6),
                        model=model_name,
                    )
            except Exception as e:
                logger.warning("openai_call_fallback_to_mock", error=str(e))

        # Real Anthropic Provider
        if self.provider == "anthropic" and settings.ANTHROPIC_API_KEY and settings.ANTHROPIC_API_KEY != "mock-key":
            try:
                async with httpx.AsyncClient(timeout=60.0) as client:
                    headers = {
                        "x-api-key": settings.ANTHROPIC_API_KEY,
                        "anthropic-version": "2023-06-01",
                        "Content-Type": "application/json",
                    }
                    payload = {
                        "model": model_name if "claude" in model_name else "claude-3-5-sonnet-20241022",
                        "system": system_prompt,
                        "messages": [{"role": "user", "content": prompt + "\nRespond strictly in valid JSON."}],
                        "max_tokens": 4096,
                        "temperature": temperature,
                    }
                    res = await client.post("https://api.anthropic.com/v1/messages", json=payload, headers=headers)
                    res.raise_for_status()
                    data = res.json()
                    text_content = data["content"][0]["text"]
                    # Extract JSON substring if formatted in markdown
                    json_match = re.search(r"\{.*\}", text_content, re.DOTALL)
                    parsed = json.loads(json_match.group(0)) if json_match else json.loads(text_content)
                    return LLMResponse(
                        text=text_content,
                        parsed_json=parsed,
                        prompt_tokens=data.get("usage", {}).get("input_tokens", 0),
                        completion_tokens=data.get("usage", {}).get("output_tokens", 0),
                        total_tokens=data.get("usage", {}).get("input_tokens", 0) + data.get("usage", {}).get("output_tokens", 0),
                        cost=0.015,
                        model=model_name,
                    )
            except Exception as e:
                logger.warning("anthropic_call_fallback_to_mock", error=str(e))

        # Default / Mock provider
        return MockLLMProvider.generate_response(prompt, system_prompt, agent_type)
